// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_jnZgJcC952CxfGFGsqsUzsj79TeLtw8',
    appId: '1:1007718571582:web:6c9c98ed6ee447a63ffb6f',
    messagingSenderId: '1007718571582',
    projectId: 'turfone-ff0e8',
    authDomain: 'turfone-ff0e8.firebaseapp.com',
    storageBucket: 'turfone-ff0e8.firebasestorage.app',
    measurementId: 'G-DC755KE85D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADhJYBXAi2xSU-swD7VAdAm7tYTE9K6YE',
    appId: '1:1007718571582:android:b58b4ae7ed2570813ffb6f',
    messagingSenderId: '1007718571582',
    projectId: 'turfone-ff0e8',
    storageBucket: 'turfone-ff0e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbZ2bmiJd1mqot-ofkURSKURFVkLu-mJk',
    appId: '1:1007718571582:ios:45014b5a63976a5a3ffb6f',
    messagingSenderId: '1007718571582',
    projectId: 'turfone-ff0e8',
    storageBucket: 'turfone-ff0e8.firebasestorage.app',
    iosBundleId: 'com.example.turfApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbZ2bmiJd1mqot-ofkURSKURFVkLu-mJk',
    appId: '1:1007718571582:ios:45014b5a63976a5a3ffb6f',
    messagingSenderId: '1007718571582',
    projectId: 'turfone-ff0e8',
    storageBucket: 'turfone-ff0e8.firebasestorage.app',
    iosBundleId: 'com.example.turfApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_jnZgJcC952CxfGFGsqsUzsj79TeLtw8',
    appId: '1:1007718571582:web:71d7de76e0e21dc93ffb6f',
    messagingSenderId: '1007718571582',
    projectId: 'turfone-ff0e8',
    authDomain: 'turfone-ff0e8.firebaseapp.com',
    storageBucket: 'turfone-ff0e8.firebasestorage.app',
    measurementId: 'G-TYCRR0YNW1',
  );
}
