// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsMDpY77RTRfwWAd94G4JKTXvBoxzFT2U',
    appId: '1:405471770959:web:1be67963b47cbebb6fed3a',
    messagingSenderId: '405471770959',
    projectId: 'turf-mate-7d89c',
    authDomain: 'turf-mate-7d89c.firebaseapp.com',
    storageBucket: 'turf-mate-7d89c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsMDpY77RTRfwWAd94G4JKTXvBoxzFT2U',
    appId: '1:405471770959:android:1be67963b47cbebb6fed3a',
    messagingSenderId: '405471770959',
    projectId: 'turf-mate-7d89c',
    storageBucket: 'turf-mate-7d89c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsMDpY77RTRfwWAd94G4JKTXvBoxzFT2U',
    appId: '1:405471770959:ios:1be67963b47cbebb6fed3a',
    messagingSenderId: '405471770959',
    projectId: 'turf-mate-7d89c',
    storageBucket: 'turf-mate-7d89c.firebasestorage.app',
    iosBundleId: 'com.example.turf-app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsMDpY77RTRfwWAd94G4JKTXvBoxzFT2U',
    appId: '1:405471770959:ios:1be67963b47cbebb6fed3a',
    messagingSenderId: '405471770959',
    projectId: 'turf-mate-7d89c',
    storageBucket: 'turf-mate-7d89c.firebasestorage.app',
    iosBundleId: 'com.example.turf-app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsMDpY77RTRfwWAd94G4JKTXvBoxzFT2U',
    appId: '1:405471770959:web:1be67963b47cbebb6fed3a',
    messagingSenderId: '405471770959',
    projectId: 'turf-mate-7d89c',
    authDomain: 'turf-mate-7d89c.firebaseapp.com',
    storageBucket: 'turf-mate-7d89c.firebasestorage.app',
  );
}
